/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Truffle } from "./types";

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface CoreVaultManagerContract
  extends Truffle.Contract<CoreVaultManagerInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<CoreVaultManagerInstance>;
}

export interface AdminChanged {
  name: "AdminChanged";
  args: {
    previousAdmin: string;
    newAdmin: string;
    0: string;
    1: string;
  };
}

export interface BeaconUpgraded {
  name: "BeaconUpgraded";
  args: {
    beacon: string;
    0: string;
  };
}

export interface EscrowFinished {
  name: "EscrowFinished";
  args: {
    preimageHash: string;
    amount: BN;
    0: string;
    1: BN;
  };
}

export interface EscrowInstructions {
  name: "EscrowInstructions";
  args: {
    sequence: BN;
    preimageHash: string;
    account: string;
    destination: string;
    amount: BN;
    cancelAfterTs: BN;
    0: BN;
    1: string;
    2: string;
    3: string;
    4: BN;
    5: BN;
  };
}

export interface GovernanceCallTimelocked {
  name: "GovernanceCallTimelocked";
  args: {
    encodedCall: string;
    encodedCallHash: string;
    allowedAfterTimestamp: BN;
    0: string;
    1: string;
    2: BN;
  };
}

export interface GovernanceInitialised {
  name: "GovernanceInitialised";
  args: {
    initialGovernance: string;
    0: string;
  };
}

export interface GovernedProductionModeEntered {
  name: "GovernedProductionModeEntered";
  args: {
    governanceSettings: string;
    0: string;
  };
}

export interface NotAllEscrowsProcessed {
  name: "NotAllEscrowsProcessed";
  args: {};
}

export interface Paused {
  name: "Paused";
  args: {};
}

export interface PaymentConfirmed {
  name: "PaymentConfirmed";
  args: {
    transactionId: string;
    amount: BN;
    0: string;
    1: BN;
  };
}

export interface PaymentInstructions {
  name: "PaymentInstructions";
  args: {
    sequence: BN;
    account: string;
    destination: string;
    amount: BN;
    0: BN;
    1: string;
    2: string;
    3: BN;
  };
}

export interface TimelockedGovernanceCallCanceled {
  name: "TimelockedGovernanceCallCanceled";
  args: {
    encodedCallHash: string;
    0: string;
  };
}

export interface TimelockedGovernanceCallExecuted {
  name: "TimelockedGovernanceCallExecuted";
  args: {
    encodedCallHash: string;
    0: string;
  };
}

export interface TransferRequestCanceled {
  name: "TransferRequestCanceled";
  args: {
    destinationAddress: string;
    amount: BN;
    0: string;
    1: BN;
  };
}

export interface TransferRequested {
  name: "TransferRequested";
  args: {
    destinationAddress: string;
    amount: BN;
    cancelable: boolean;
    0: string;
    1: BN;
    2: boolean;
  };
}

export interface Unpaused {
  name: "Unpaused";
  args: {};
}

export interface Upgraded {
  name: "Upgraded";
  args: {
    implementation: string;
    0: string;
  };
}

export type AllEvents =
  | AdminChanged
  | BeaconUpgraded
  | EscrowFinished
  | EscrowInstructions
  | GovernanceCallTimelocked
  | GovernanceInitialised
  | GovernedProductionModeEntered
  | NotAllEscrowsProcessed
  | Paused
  | PaymentConfirmed
  | PaymentInstructions
  | TimelockedGovernanceCallCanceled
  | TimelockedGovernanceCallExecuted
  | TransferRequestCanceled
  | TransferRequested
  | Unpaused
  | Upgraded;

export interface CoreVaultManagerInstance extends Truffle.ContractInstance {
  addAllowedDestinationAddresses: {
    (
      _allowedDestinationAddresses: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _allowedDestinationAddresses: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _allowedDestinationAddresses: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _allowedDestinationAddresses: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  addEmergencyPauseSenders: {
    (_addresses: string[], txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _addresses: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _addresses: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _addresses: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  addPreimageHashes: {
    (
      _preimageHashes: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _preimageHashes: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _preimageHashes: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _preimageHashes: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  addTriggeringAccounts: {
    (
      _triggeringAccounts: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _triggeringAccounts: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _triggeringAccounts: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _triggeringAccounts: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  assetManager(txDetails?: Truffle.TransactionDetails): Promise<string>;

  availableFunds(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  cancelGovernanceCall: {
    (_encodedCall: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _encodedCall: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _encodedCall: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _encodedCall: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  cancelTransferRequestFromCoreVault: {
    (
      _destinationAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _destinationAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _destinationAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _destinationAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  cancelableTransferRequestsAmount(
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  chainId(txDetails?: Truffle.TransactionDetails): Promise<string>;

  confirmPayment: {
    (
      _proof: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionId: string;
            inUtxo: number | BN | string;
            utxo: number | BN | string;
          };
          responseBody: {
            blockNumber: number | BN | string;
            blockTimestamp: number | BN | string;
            sourceAddressHash: string;
            sourceAddressesRoot: string;
            receivingAddressHash: string;
            intendedReceivingAddressHash: string;
            spentAmount: number | BN | string;
            intendedSpentAmount: number | BN | string;
            receivedAmount: number | BN | string;
            intendedReceivedAmount: number | BN | string;
            standardPaymentReference: string;
            oneToOne: boolean;
            status: number | BN | string;
          };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _proof: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionId: string;
            inUtxo: number | BN | string;
            utxo: number | BN | string;
          };
          responseBody: {
            blockNumber: number | BN | string;
            blockTimestamp: number | BN | string;
            sourceAddressHash: string;
            sourceAddressesRoot: string;
            receivingAddressHash: string;
            intendedReceivingAddressHash: string;
            spentAmount: number | BN | string;
            intendedSpentAmount: number | BN | string;
            receivedAmount: number | BN | string;
            intendedReceivedAmount: number | BN | string;
            standardPaymentReference: string;
            oneToOne: boolean;
            status: number | BN | string;
          };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _proof: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionId: string;
            inUtxo: number | BN | string;
            utxo: number | BN | string;
          };
          responseBody: {
            blockNumber: number | BN | string;
            blockTimestamp: number | BN | string;
            sourceAddressHash: string;
            sourceAddressesRoot: string;
            receivingAddressHash: string;
            intendedReceivingAddressHash: string;
            spentAmount: number | BN | string;
            intendedSpentAmount: number | BN | string;
            receivedAmount: number | BN | string;
            intendedReceivedAmount: number | BN | string;
            standardPaymentReference: string;
            oneToOne: boolean;
            status: number | BN | string;
          };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _proof: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionId: string;
            inUtxo: number | BN | string;
            utxo: number | BN | string;
          };
          responseBody: {
            blockNumber: number | BN | string;
            blockTimestamp: number | BN | string;
            sourceAddressHash: string;
            sourceAddressesRoot: string;
            receivingAddressHash: string;
            intendedReceivingAddressHash: string;
            spentAmount: number | BN | string;
            intendedSpentAmount: number | BN | string;
            receivedAmount: number | BN | string;
            intendedReceivedAmount: number | BN | string;
            standardPaymentReference: string;
            oneToOne: boolean;
            status: number | BN | string;
          };
        };
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  confirmedPayments(
    transactionId: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  coreVaultAddress(txDetails?: Truffle.TransactionDetails): Promise<string>;

  coreVaultAddressHash(txDetails?: Truffle.TransactionDetails): Promise<string>;

  custodianAddress(txDetails?: Truffle.TransactionDetails): Promise<string>;

  escrowAmount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  escrowEndTimeSeconds(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  escrowedFunds(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  executeGovernanceCall: {
    (_encodedCall: string, txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _encodedCall: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _encodedCall: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _encodedCall: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  fdcVerification(txDetails?: Truffle.TransactionDetails): Promise<string>;

  getAddressUpdater(txDetails?: Truffle.TransactionDetails): Promise<string>;

  getAllowedDestinationAddresses(
    txDetails?: Truffle.TransactionDetails
  ): Promise<string[]>;

  getCancelableTransferRequests(
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ destinationAddress: string; amount: BN }[]>;

  getEmergencyPauseSenders(
    txDetails?: Truffle.TransactionDetails
  ): Promise<string[]>;

  getEscrowByIndex(
    _index: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    preimageHash: string;
    amount: BN;
    expiryTs: BN;
    finished: boolean;
  }>;

  getEscrowByPreimageHash(
    _preimageHash: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{
    preimageHash: string;
    amount: BN;
    expiryTs: BN;
    finished: boolean;
  }>;

  getEscrowsCount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  getNonCancelableTransferRequests(
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ destinationAddress: string; amount: BN }[]>;

  getPreimageHash(
    _index: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  getPreimageHashesCount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  getTriggeringAccounts(
    txDetails?: Truffle.TransactionDetails
  ): Promise<string[]>;

  getUnprocessedEscrows(
    txDetails?: Truffle.TransactionDetails
  ): Promise<
    { preimageHash: string; amount: BN; expiryTs: BN; finished: boolean }[]
  >;

  getUnusedPreimageHashes(
    txDetails?: Truffle.TransactionDetails
  ): Promise<string[]>;

  governance(txDetails?: Truffle.TransactionDetails): Promise<string>;

  governanceSettings(txDetails?: Truffle.TransactionDetails): Promise<string>;

  initialise: {
    (
      _governanceSettings: string,
      _initialGovernance: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _governanceSettings: string,
      _initialGovernance: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _governanceSettings: string,
      _initialGovernance: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _governanceSettings: string,
      _initialGovernance: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  initialize: {
    (
      _governanceSettings: string,
      _initialGovernance: string,
      _addressUpdater: string,
      _assetManager: string,
      _chainId: string,
      _custodianAddress: string,
      _coreVaultAddress: string,
      _nextSequenceNumber: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _governanceSettings: string,
      _initialGovernance: string,
      _addressUpdater: string,
      _assetManager: string,
      _chainId: string,
      _custodianAddress: string,
      _coreVaultAddress: string,
      _nextSequenceNumber: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _governanceSettings: string,
      _initialGovernance: string,
      _addressUpdater: string,
      _assetManager: string,
      _chainId: string,
      _custodianAddress: string,
      _coreVaultAddress: string,
      _nextSequenceNumber: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _governanceSettings: string,
      _initialGovernance: string,
      _addressUpdater: string,
      _assetManager: string,
      _chainId: string,
      _custodianAddress: string,
      _coreVaultAddress: string,
      _nextSequenceNumber: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  isDestinationAddressAllowed(
    _address: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  isExecutor(
    _address: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  minimalAmount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  nextSequenceNumber(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  nextUnprocessedEscrowIndex(
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  nextUnusedPreimageHashIndex(
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  nonCancelableTransferRequestsAmount(
    txDetails?: Truffle.TransactionDetails
  ): Promise<BN>;

  pause: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  paused(txDetails?: Truffle.TransactionDetails): Promise<boolean>;

  processEscrows: {
    (
      _maxCount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _maxCount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;
    sendTransaction(
      _maxCount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _maxCount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  productionMode(txDetails?: Truffle.TransactionDetails): Promise<boolean>;

  proxiableUUID(txDetails?: Truffle.TransactionDetails): Promise<string>;

  removeAllowedDestinationAddresses: {
    (
      _allowedDestinationAddresses: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _allowedDestinationAddresses: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _allowedDestinationAddresses: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _allowedDestinationAddresses: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  removeEmergencyPauseSenders: {
    (_addresses: string[], txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(
      _addresses: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _addresses: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _addresses: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  removeTriggeringAccounts: {
    (
      _triggeringAccounts: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _triggeringAccounts: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _triggeringAccounts: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _triggeringAccounts: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  removeUnusedPreimageHashes: {
    (
      _maxCount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _maxCount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _maxCount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _maxCount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  requestTransferFromCoreVault: {
    (
      _destinationAddress: string,
      _amount: number | BN | string,
      _cancelable: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _destinationAddress: string,
      _amount: number | BN | string,
      _cancelable: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _destinationAddress: string,
      _amount: number | BN | string,
      _cancelable: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _destinationAddress: string,
      _amount: number | BN | string,
      _cancelable: boolean,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  setEscrowsFinished: {
    (
      _preimageHashes: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _preimageHashes: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _preimageHashes: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _preimageHashes: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  supportsInterface(
    _interfaceId: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  switchToProductionMode: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  triggerInstructions: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  unpause: {
    (txDetails?: Truffle.TransactionDetails): Promise<
      Truffle.TransactionResponse<AllEvents>
    >;
    call(txDetails?: Truffle.TransactionDetails): Promise<void>;
    sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
    estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
  };

  updateContractAddresses: {
    (
      _contractNameHashes: string[],
      _contractAddresses: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _contractNameHashes: string[],
      _contractAddresses: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _contractNameHashes: string[],
      _contractAddresses: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _contractNameHashes: string[],
      _contractAddresses: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  updateCustodianAddress: {
    (
      _custodianAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _custodianAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _custodianAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _custodianAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  updateSettings: {
    (
      _escrowEndTimeSeconds: number | BN | string,
      _escrowAmount: number | BN | string,
      _minimalAmount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _escrowEndTimeSeconds: number | BN | string,
      _escrowAmount: number | BN | string,
      _minimalAmount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _escrowEndTimeSeconds: number | BN | string,
      _escrowAmount: number | BN | string,
      _minimalAmount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _escrowEndTimeSeconds: number | BN | string,
      _escrowAmount: number | BN | string,
      _minimalAmount: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  upgradeTo: {
    (
      newImplementation: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      newImplementation: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      newImplementation: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      newImplementation: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  upgradeToAndCall: {
    (
      newImplementation: string,
      data: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      newImplementation: string,
      data: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      newImplementation: string,
      data: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      newImplementation: string,
      data: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    addAllowedDestinationAddresses: {
      (
        _allowedDestinationAddresses: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _allowedDestinationAddresses: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _allowedDestinationAddresses: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _allowedDestinationAddresses: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    addEmergencyPauseSenders: {
      (_addresses: string[], txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _addresses: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _addresses: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _addresses: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    addPreimageHashes: {
      (
        _preimageHashes: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _preimageHashes: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _preimageHashes: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _preimageHashes: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    addTriggeringAccounts: {
      (
        _triggeringAccounts: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _triggeringAccounts: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _triggeringAccounts: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _triggeringAccounts: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    assetManager(txDetails?: Truffle.TransactionDetails): Promise<string>;

    availableFunds(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    cancelGovernanceCall: {
      (_encodedCall: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _encodedCall: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _encodedCall: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _encodedCall: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    cancelTransferRequestFromCoreVault: {
      (
        _destinationAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _destinationAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _destinationAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _destinationAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    cancelableTransferRequestsAmount(
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    chainId(txDetails?: Truffle.TransactionDetails): Promise<string>;

    confirmPayment: {
      (
        _proof: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionId: string;
              inUtxo: number | BN | string;
              utxo: number | BN | string;
            };
            responseBody: {
              blockNumber: number | BN | string;
              blockTimestamp: number | BN | string;
              sourceAddressHash: string;
              sourceAddressesRoot: string;
              receivingAddressHash: string;
              intendedReceivingAddressHash: string;
              spentAmount: number | BN | string;
              intendedSpentAmount: number | BN | string;
              receivedAmount: number | BN | string;
              intendedReceivedAmount: number | BN | string;
              standardPaymentReference: string;
              oneToOne: boolean;
              status: number | BN | string;
            };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _proof: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionId: string;
              inUtxo: number | BN | string;
              utxo: number | BN | string;
            };
            responseBody: {
              blockNumber: number | BN | string;
              blockTimestamp: number | BN | string;
              sourceAddressHash: string;
              sourceAddressesRoot: string;
              receivingAddressHash: string;
              intendedReceivingAddressHash: string;
              spentAmount: number | BN | string;
              intendedSpentAmount: number | BN | string;
              receivedAmount: number | BN | string;
              intendedReceivedAmount: number | BN | string;
              standardPaymentReference: string;
              oneToOne: boolean;
              status: number | BN | string;
            };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _proof: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionId: string;
              inUtxo: number | BN | string;
              utxo: number | BN | string;
            };
            responseBody: {
              blockNumber: number | BN | string;
              blockTimestamp: number | BN | string;
              sourceAddressHash: string;
              sourceAddressesRoot: string;
              receivingAddressHash: string;
              intendedReceivingAddressHash: string;
              spentAmount: number | BN | string;
              intendedSpentAmount: number | BN | string;
              receivedAmount: number | BN | string;
              intendedReceivedAmount: number | BN | string;
              standardPaymentReference: string;
              oneToOne: boolean;
              status: number | BN | string;
            };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _proof: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionId: string;
              inUtxo: number | BN | string;
              utxo: number | BN | string;
            };
            responseBody: {
              blockNumber: number | BN | string;
              blockTimestamp: number | BN | string;
              sourceAddressHash: string;
              sourceAddressesRoot: string;
              receivingAddressHash: string;
              intendedReceivingAddressHash: string;
              spentAmount: number | BN | string;
              intendedSpentAmount: number | BN | string;
              receivedAmount: number | BN | string;
              intendedReceivedAmount: number | BN | string;
              standardPaymentReference: string;
              oneToOne: boolean;
              status: number | BN | string;
            };
          };
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    confirmedPayments(
      transactionId: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    coreVaultAddress(txDetails?: Truffle.TransactionDetails): Promise<string>;

    coreVaultAddressHash(
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    custodianAddress(txDetails?: Truffle.TransactionDetails): Promise<string>;

    escrowAmount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    escrowEndTimeSeconds(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    escrowedFunds(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    executeGovernanceCall: {
      (_encodedCall: string, txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _encodedCall: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _encodedCall: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _encodedCall: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    fdcVerification(txDetails?: Truffle.TransactionDetails): Promise<string>;

    getAddressUpdater(txDetails?: Truffle.TransactionDetails): Promise<string>;

    getAllowedDestinationAddresses(
      txDetails?: Truffle.TransactionDetails
    ): Promise<string[]>;

    getCancelableTransferRequests(
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ destinationAddress: string; amount: BN }[]>;

    getEmergencyPauseSenders(
      txDetails?: Truffle.TransactionDetails
    ): Promise<string[]>;

    getEscrowByIndex(
      _index: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      preimageHash: string;
      amount: BN;
      expiryTs: BN;
      finished: boolean;
    }>;

    getEscrowByPreimageHash(
      _preimageHash: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{
      preimageHash: string;
      amount: BN;
      expiryTs: BN;
      finished: boolean;
    }>;

    getEscrowsCount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    getNonCancelableTransferRequests(
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ destinationAddress: string; amount: BN }[]>;

    getPreimageHash(
      _index: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    getPreimageHashesCount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    getTriggeringAccounts(
      txDetails?: Truffle.TransactionDetails
    ): Promise<string[]>;

    getUnprocessedEscrows(
      txDetails?: Truffle.TransactionDetails
    ): Promise<
      { preimageHash: string; amount: BN; expiryTs: BN; finished: boolean }[]
    >;

    getUnusedPreimageHashes(
      txDetails?: Truffle.TransactionDetails
    ): Promise<string[]>;

    governance(txDetails?: Truffle.TransactionDetails): Promise<string>;

    governanceSettings(txDetails?: Truffle.TransactionDetails): Promise<string>;

    initialise: {
      (
        _governanceSettings: string,
        _initialGovernance: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _governanceSettings: string,
        _initialGovernance: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _governanceSettings: string,
        _initialGovernance: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _governanceSettings: string,
        _initialGovernance: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    initialize: {
      (
        _governanceSettings: string,
        _initialGovernance: string,
        _addressUpdater: string,
        _assetManager: string,
        _chainId: string,
        _custodianAddress: string,
        _coreVaultAddress: string,
        _nextSequenceNumber: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _governanceSettings: string,
        _initialGovernance: string,
        _addressUpdater: string,
        _assetManager: string,
        _chainId: string,
        _custodianAddress: string,
        _coreVaultAddress: string,
        _nextSequenceNumber: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _governanceSettings: string,
        _initialGovernance: string,
        _addressUpdater: string,
        _assetManager: string,
        _chainId: string,
        _custodianAddress: string,
        _coreVaultAddress: string,
        _nextSequenceNumber: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _governanceSettings: string,
        _initialGovernance: string,
        _addressUpdater: string,
        _assetManager: string,
        _chainId: string,
        _custodianAddress: string,
        _coreVaultAddress: string,
        _nextSequenceNumber: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    isDestinationAddressAllowed(
      _address: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    isExecutor(
      _address: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    minimalAmount(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    nextSequenceNumber(txDetails?: Truffle.TransactionDetails): Promise<BN>;

    nextUnprocessedEscrowIndex(
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    nextUnusedPreimageHashIndex(
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    nonCancelableTransferRequestsAmount(
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;

    pause: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    paused(txDetails?: Truffle.TransactionDetails): Promise<boolean>;

    processEscrows: {
      (
        _maxCount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _maxCount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<boolean>;
      sendTransaction(
        _maxCount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _maxCount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    productionMode(txDetails?: Truffle.TransactionDetails): Promise<boolean>;

    proxiableUUID(txDetails?: Truffle.TransactionDetails): Promise<string>;

    removeAllowedDestinationAddresses: {
      (
        _allowedDestinationAddresses: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _allowedDestinationAddresses: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _allowedDestinationAddresses: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _allowedDestinationAddresses: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    removeEmergencyPauseSenders: {
      (_addresses: string[], txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(
        _addresses: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _addresses: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _addresses: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    removeTriggeringAccounts: {
      (
        _triggeringAccounts: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _triggeringAccounts: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _triggeringAccounts: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _triggeringAccounts: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    removeUnusedPreimageHashes: {
      (
        _maxCount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _maxCount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _maxCount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _maxCount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    requestTransferFromCoreVault: {
      (
        _destinationAddress: string,
        _amount: number | BN | string,
        _cancelable: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _destinationAddress: string,
        _amount: number | BN | string,
        _cancelable: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _destinationAddress: string,
        _amount: number | BN | string,
        _cancelable: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _destinationAddress: string,
        _amount: number | BN | string,
        _cancelable: boolean,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    setEscrowsFinished: {
      (
        _preimageHashes: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _preimageHashes: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _preimageHashes: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _preimageHashes: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    supportsInterface(
      _interfaceId: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;

    switchToProductionMode: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    triggerInstructions: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    unpause: {
      (txDetails?: Truffle.TransactionDetails): Promise<
        Truffle.TransactionResponse<AllEvents>
      >;
      call(txDetails?: Truffle.TransactionDetails): Promise<void>;
      sendTransaction(txDetails?: Truffle.TransactionDetails): Promise<string>;
      estimateGas(txDetails?: Truffle.TransactionDetails): Promise<number>;
    };

    updateContractAddresses: {
      (
        _contractNameHashes: string[],
        _contractAddresses: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _contractNameHashes: string[],
        _contractAddresses: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _contractNameHashes: string[],
        _contractAddresses: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _contractNameHashes: string[],
        _contractAddresses: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    updateCustodianAddress: {
      (
        _custodianAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _custodianAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _custodianAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _custodianAddress: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    updateSettings: {
      (
        _escrowEndTimeSeconds: number | BN | string,
        _escrowAmount: number | BN | string,
        _minimalAmount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _escrowEndTimeSeconds: number | BN | string,
        _escrowAmount: number | BN | string,
        _minimalAmount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _escrowEndTimeSeconds: number | BN | string,
        _escrowAmount: number | BN | string,
        _minimalAmount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _escrowEndTimeSeconds: number | BN | string,
        _escrowAmount: number | BN | string,
        _minimalAmount: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    upgradeTo: {
      (
        newImplementation: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        newImplementation: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        newImplementation: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        newImplementation: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    upgradeToAndCall: {
      (
        newImplementation: string,
        data: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        newImplementation: string,
        data: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        newImplementation: string,
        data: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        newImplementation: string,
        data: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
