/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Truffle } from "./types";

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IAgentAlwaysAllowedMintersContract
  extends Truffle.Contract<IAgentAlwaysAllowedMintersInstance> {
  "new"(
    meta?: Truffle.TransactionDetails
  ): Promise<IAgentAlwaysAllowedMintersInstance>;
}

export type AllEvents = never;

export interface IAgentAlwaysAllowedMintersInstance
  extends Truffle.ContractInstance {
  addAlwaysAllowedMinterForAgent: {
    (
      _agentVault: string,
      _minter: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _agentVault: string,
      _minter: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _agentVault: string,
      _minter: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _agentVault: string,
      _minter: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  alwaysAllowedMintersForAgent(
    _agentVault: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string[]>;

  removeAlwaysAllowedMinterForAgent: {
    (
      _agentVault: string,
      _minter: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _agentVault: string,
      _minter: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _agentVault: string,
      _minter: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _agentVault: string,
      _minter: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    addAlwaysAllowedMinterForAgent: {
      (
        _agentVault: string,
        _minter: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _agentVault: string,
        _minter: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _agentVault: string,
        _minter: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _agentVault: string,
        _minter: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    alwaysAllowedMintersForAgent(
      _agentVault: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string[]>;

    removeAlwaysAllowedMinterForAgent: {
      (
        _agentVault: string,
        _minter: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _agentVault: string,
        _minter: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _agentVault: string,
        _minter: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _agentVault: string,
        _minter: string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
