/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Truffle } from "./types";

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IChallengerContract
  extends Truffle.Contract<IChallengerInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<IChallengerInstance>;
}

export type AllEvents = never;

export interface IChallengerInstance extends Truffle.ContractInstance {
  doublePaymentChallenge: {
    (
      _payment1: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionId: string;
            sourceAddressIndicator: string;
          };
          responseBody: {
            blockNumber: number | BN | string;
            blockTimestamp: number | BN | string;
            sourceAddressHash: string;
            spentAmount: number | BN | string;
            standardPaymentReference: string;
          };
        };
      },
      _payment2: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionId: string;
            sourceAddressIndicator: string;
          };
          responseBody: {
            blockNumber: number | BN | string;
            blockTimestamp: number | BN | string;
            sourceAddressHash: string;
            spentAmount: number | BN | string;
            standardPaymentReference: string;
          };
        };
      },
      _agentVault: string,
      _vaultToFAssetMinDexPriceMul: number | BN | string,
      _vaultToFAssetMinDexPriceDiv: number | BN | string,
      _poolToVaultMinDexPriceMul: number | BN | string,
      _poolToVaultMinDexPriceDiv: number | BN | string,
      _flashLender: string,
      _dex: string,
      _vaultToFAssetDexPath: string[],
      _poolToVaultDexPath: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _payment1: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionId: string;
            sourceAddressIndicator: string;
          };
          responseBody: {
            blockNumber: number | BN | string;
            blockTimestamp: number | BN | string;
            sourceAddressHash: string;
            spentAmount: number | BN | string;
            standardPaymentReference: string;
          };
        };
      },
      _payment2: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionId: string;
            sourceAddressIndicator: string;
          };
          responseBody: {
            blockNumber: number | BN | string;
            blockTimestamp: number | BN | string;
            sourceAddressHash: string;
            spentAmount: number | BN | string;
            standardPaymentReference: string;
          };
        };
      },
      _agentVault: string,
      _vaultToFAssetMinDexPriceMul: number | BN | string,
      _vaultToFAssetMinDexPriceDiv: number | BN | string,
      _poolToVaultMinDexPriceMul: number | BN | string,
      _poolToVaultMinDexPriceDiv: number | BN | string,
      _flashLender: string,
      _dex: string,
      _vaultToFAssetDexPath: string[],
      _poolToVaultDexPath: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _payment1: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionId: string;
            sourceAddressIndicator: string;
          };
          responseBody: {
            blockNumber: number | BN | string;
            blockTimestamp: number | BN | string;
            sourceAddressHash: string;
            spentAmount: number | BN | string;
            standardPaymentReference: string;
          };
        };
      },
      _payment2: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionId: string;
            sourceAddressIndicator: string;
          };
          responseBody: {
            blockNumber: number | BN | string;
            blockTimestamp: number | BN | string;
            sourceAddressHash: string;
            spentAmount: number | BN | string;
            standardPaymentReference: string;
          };
        };
      },
      _agentVault: string,
      _vaultToFAssetMinDexPriceMul: number | BN | string,
      _vaultToFAssetMinDexPriceDiv: number | BN | string,
      _poolToVaultMinDexPriceMul: number | BN | string,
      _poolToVaultMinDexPriceDiv: number | BN | string,
      _flashLender: string,
      _dex: string,
      _vaultToFAssetDexPath: string[],
      _poolToVaultDexPath: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _payment1: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionId: string;
            sourceAddressIndicator: string;
          };
          responseBody: {
            blockNumber: number | BN | string;
            blockTimestamp: number | BN | string;
            sourceAddressHash: string;
            spentAmount: number | BN | string;
            standardPaymentReference: string;
          };
        };
      },
      _payment2: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionId: string;
            sourceAddressIndicator: string;
          };
          responseBody: {
            blockNumber: number | BN | string;
            blockTimestamp: number | BN | string;
            sourceAddressHash: string;
            spentAmount: number | BN | string;
            standardPaymentReference: string;
          };
        };
      },
      _agentVault: string,
      _vaultToFAssetMinDexPriceMul: number | BN | string,
      _vaultToFAssetMinDexPriceDiv: number | BN | string,
      _poolToVaultMinDexPriceMul: number | BN | string,
      _poolToVaultMinDexPriceDiv: number | BN | string,
      _flashLender: string,
      _dex: string,
      _vaultToFAssetDexPath: string[],
      _poolToVaultDexPath: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  freeBalanceNegativeChallenge: {
    (
      _payments: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionId: string;
            sourceAddressIndicator: string;
          };
          responseBody: {
            blockNumber: number | BN | string;
            blockTimestamp: number | BN | string;
            sourceAddressHash: string;
            spentAmount: number | BN | string;
            standardPaymentReference: string;
          };
        };
      }[],
      _agentVault: string,
      _vaultToFAssetMinDexPriceMul: number | BN | string,
      _vaultToFAssetMinDexPriceDiv: number | BN | string,
      _poolToVaultMinDexPriceMul: number | BN | string,
      _poolToVaultMinDexPriceDiv: number | BN | string,
      _flashLender: string,
      _dex: string,
      _vaultToFAssetDexPath: string[],
      _poolToVaultDexPath: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _payments: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionId: string;
            sourceAddressIndicator: string;
          };
          responseBody: {
            blockNumber: number | BN | string;
            blockTimestamp: number | BN | string;
            sourceAddressHash: string;
            spentAmount: number | BN | string;
            standardPaymentReference: string;
          };
        };
      }[],
      _agentVault: string,
      _vaultToFAssetMinDexPriceMul: number | BN | string,
      _vaultToFAssetMinDexPriceDiv: number | BN | string,
      _poolToVaultMinDexPriceMul: number | BN | string,
      _poolToVaultMinDexPriceDiv: number | BN | string,
      _flashLender: string,
      _dex: string,
      _vaultToFAssetDexPath: string[],
      _poolToVaultDexPath: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _payments: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionId: string;
            sourceAddressIndicator: string;
          };
          responseBody: {
            blockNumber: number | BN | string;
            blockTimestamp: number | BN | string;
            sourceAddressHash: string;
            spentAmount: number | BN | string;
            standardPaymentReference: string;
          };
        };
      }[],
      _agentVault: string,
      _vaultToFAssetMinDexPriceMul: number | BN | string,
      _vaultToFAssetMinDexPriceDiv: number | BN | string,
      _poolToVaultMinDexPriceMul: number | BN | string,
      _poolToVaultMinDexPriceDiv: number | BN | string,
      _flashLender: string,
      _dex: string,
      _vaultToFAssetDexPath: string[],
      _poolToVaultDexPath: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _payments: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionId: string;
            sourceAddressIndicator: string;
          };
          responseBody: {
            blockNumber: number | BN | string;
            blockTimestamp: number | BN | string;
            sourceAddressHash: string;
            spentAmount: number | BN | string;
            standardPaymentReference: string;
          };
        };
      }[],
      _agentVault: string,
      _vaultToFAssetMinDexPriceMul: number | BN | string,
      _vaultToFAssetMinDexPriceDiv: number | BN | string,
      _poolToVaultMinDexPriceMul: number | BN | string,
      _poolToVaultMinDexPriceDiv: number | BN | string,
      _flashLender: string,
      _dex: string,
      _vaultToFAssetDexPath: string[],
      _poolToVaultDexPath: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  illegalPaymentChallenge: {
    (
      _transaction: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionId: string;
            sourceAddressIndicator: string;
          };
          responseBody: {
            blockNumber: number | BN | string;
            blockTimestamp: number | BN | string;
            sourceAddressHash: string;
            spentAmount: number | BN | string;
            standardPaymentReference: string;
          };
        };
      },
      _agentVault: string,
      _vaultToFAssetMinDexPriceMul: number | BN | string,
      _vaultToFAssetMinDexPriceDiv: number | BN | string,
      _poolToVaultMinDexPriceMul: number | BN | string,
      _poolToVaultMinDexPriceDiv: number | BN | string,
      _flashLender: string,
      _dex: string,
      _vaultToFAssetDexPath: string[],
      _poolToVaultDexPath: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _transaction: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionId: string;
            sourceAddressIndicator: string;
          };
          responseBody: {
            blockNumber: number | BN | string;
            blockTimestamp: number | BN | string;
            sourceAddressHash: string;
            spentAmount: number | BN | string;
            standardPaymentReference: string;
          };
        };
      },
      _agentVault: string,
      _vaultToFAssetMinDexPriceMul: number | BN | string,
      _vaultToFAssetMinDexPriceDiv: number | BN | string,
      _poolToVaultMinDexPriceMul: number | BN | string,
      _poolToVaultMinDexPriceDiv: number | BN | string,
      _flashLender: string,
      _dex: string,
      _vaultToFAssetDexPath: string[],
      _poolToVaultDexPath: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _transaction: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionId: string;
            sourceAddressIndicator: string;
          };
          responseBody: {
            blockNumber: number | BN | string;
            blockTimestamp: number | BN | string;
            sourceAddressHash: string;
            spentAmount: number | BN | string;
            standardPaymentReference: string;
          };
        };
      },
      _agentVault: string,
      _vaultToFAssetMinDexPriceMul: number | BN | string,
      _vaultToFAssetMinDexPriceDiv: number | BN | string,
      _poolToVaultMinDexPriceMul: number | BN | string,
      _poolToVaultMinDexPriceDiv: number | BN | string,
      _flashLender: string,
      _dex: string,
      _vaultToFAssetDexPath: string[],
      _poolToVaultDexPath: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _transaction: {
        merkleProof: string[];
        data: {
          attestationType: string;
          sourceId: string;
          votingRound: number | BN | string;
          lowestUsedTimestamp: number | BN | string;
          requestBody: {
            transactionId: string;
            sourceAddressIndicator: string;
          };
          responseBody: {
            blockNumber: number | BN | string;
            blockTimestamp: number | BN | string;
            sourceAddressHash: string;
            spentAmount: number | BN | string;
            standardPaymentReference: string;
          };
        };
      },
      _agentVault: string,
      _vaultToFAssetMinDexPriceMul: number | BN | string,
      _vaultToFAssetMinDexPriceDiv: number | BN | string,
      _poolToVaultMinDexPriceMul: number | BN | string,
      _poolToVaultMinDexPriceDiv: number | BN | string,
      _flashLender: string,
      _dex: string,
      _vaultToFAssetDexPath: string[],
      _poolToVaultDexPath: string[],
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    doublePaymentChallenge: {
      (
        _payment1: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionId: string;
              sourceAddressIndicator: string;
            };
            responseBody: {
              blockNumber: number | BN | string;
              blockTimestamp: number | BN | string;
              sourceAddressHash: string;
              spentAmount: number | BN | string;
              standardPaymentReference: string;
            };
          };
        },
        _payment2: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionId: string;
              sourceAddressIndicator: string;
            };
            responseBody: {
              blockNumber: number | BN | string;
              blockTimestamp: number | BN | string;
              sourceAddressHash: string;
              spentAmount: number | BN | string;
              standardPaymentReference: string;
            };
          };
        },
        _agentVault: string,
        _vaultToFAssetMinDexPriceMul: number | BN | string,
        _vaultToFAssetMinDexPriceDiv: number | BN | string,
        _poolToVaultMinDexPriceMul: number | BN | string,
        _poolToVaultMinDexPriceDiv: number | BN | string,
        _flashLender: string,
        _dex: string,
        _vaultToFAssetDexPath: string[],
        _poolToVaultDexPath: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _payment1: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionId: string;
              sourceAddressIndicator: string;
            };
            responseBody: {
              blockNumber: number | BN | string;
              blockTimestamp: number | BN | string;
              sourceAddressHash: string;
              spentAmount: number | BN | string;
              standardPaymentReference: string;
            };
          };
        },
        _payment2: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionId: string;
              sourceAddressIndicator: string;
            };
            responseBody: {
              blockNumber: number | BN | string;
              blockTimestamp: number | BN | string;
              sourceAddressHash: string;
              spentAmount: number | BN | string;
              standardPaymentReference: string;
            };
          };
        },
        _agentVault: string,
        _vaultToFAssetMinDexPriceMul: number | BN | string,
        _vaultToFAssetMinDexPriceDiv: number | BN | string,
        _poolToVaultMinDexPriceMul: number | BN | string,
        _poolToVaultMinDexPriceDiv: number | BN | string,
        _flashLender: string,
        _dex: string,
        _vaultToFAssetDexPath: string[],
        _poolToVaultDexPath: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _payment1: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionId: string;
              sourceAddressIndicator: string;
            };
            responseBody: {
              blockNumber: number | BN | string;
              blockTimestamp: number | BN | string;
              sourceAddressHash: string;
              spentAmount: number | BN | string;
              standardPaymentReference: string;
            };
          };
        },
        _payment2: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionId: string;
              sourceAddressIndicator: string;
            };
            responseBody: {
              blockNumber: number | BN | string;
              blockTimestamp: number | BN | string;
              sourceAddressHash: string;
              spentAmount: number | BN | string;
              standardPaymentReference: string;
            };
          };
        },
        _agentVault: string,
        _vaultToFAssetMinDexPriceMul: number | BN | string,
        _vaultToFAssetMinDexPriceDiv: number | BN | string,
        _poolToVaultMinDexPriceMul: number | BN | string,
        _poolToVaultMinDexPriceDiv: number | BN | string,
        _flashLender: string,
        _dex: string,
        _vaultToFAssetDexPath: string[],
        _poolToVaultDexPath: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _payment1: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionId: string;
              sourceAddressIndicator: string;
            };
            responseBody: {
              blockNumber: number | BN | string;
              blockTimestamp: number | BN | string;
              sourceAddressHash: string;
              spentAmount: number | BN | string;
              standardPaymentReference: string;
            };
          };
        },
        _payment2: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionId: string;
              sourceAddressIndicator: string;
            };
            responseBody: {
              blockNumber: number | BN | string;
              blockTimestamp: number | BN | string;
              sourceAddressHash: string;
              spentAmount: number | BN | string;
              standardPaymentReference: string;
            };
          };
        },
        _agentVault: string,
        _vaultToFAssetMinDexPriceMul: number | BN | string,
        _vaultToFAssetMinDexPriceDiv: number | BN | string,
        _poolToVaultMinDexPriceMul: number | BN | string,
        _poolToVaultMinDexPriceDiv: number | BN | string,
        _flashLender: string,
        _dex: string,
        _vaultToFAssetDexPath: string[],
        _poolToVaultDexPath: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    freeBalanceNegativeChallenge: {
      (
        _payments: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionId: string;
              sourceAddressIndicator: string;
            };
            responseBody: {
              blockNumber: number | BN | string;
              blockTimestamp: number | BN | string;
              sourceAddressHash: string;
              spentAmount: number | BN | string;
              standardPaymentReference: string;
            };
          };
        }[],
        _agentVault: string,
        _vaultToFAssetMinDexPriceMul: number | BN | string,
        _vaultToFAssetMinDexPriceDiv: number | BN | string,
        _poolToVaultMinDexPriceMul: number | BN | string,
        _poolToVaultMinDexPriceDiv: number | BN | string,
        _flashLender: string,
        _dex: string,
        _vaultToFAssetDexPath: string[],
        _poolToVaultDexPath: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _payments: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionId: string;
              sourceAddressIndicator: string;
            };
            responseBody: {
              blockNumber: number | BN | string;
              blockTimestamp: number | BN | string;
              sourceAddressHash: string;
              spentAmount: number | BN | string;
              standardPaymentReference: string;
            };
          };
        }[],
        _agentVault: string,
        _vaultToFAssetMinDexPriceMul: number | BN | string,
        _vaultToFAssetMinDexPriceDiv: number | BN | string,
        _poolToVaultMinDexPriceMul: number | BN | string,
        _poolToVaultMinDexPriceDiv: number | BN | string,
        _flashLender: string,
        _dex: string,
        _vaultToFAssetDexPath: string[],
        _poolToVaultDexPath: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _payments: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionId: string;
              sourceAddressIndicator: string;
            };
            responseBody: {
              blockNumber: number | BN | string;
              blockTimestamp: number | BN | string;
              sourceAddressHash: string;
              spentAmount: number | BN | string;
              standardPaymentReference: string;
            };
          };
        }[],
        _agentVault: string,
        _vaultToFAssetMinDexPriceMul: number | BN | string,
        _vaultToFAssetMinDexPriceDiv: number | BN | string,
        _poolToVaultMinDexPriceMul: number | BN | string,
        _poolToVaultMinDexPriceDiv: number | BN | string,
        _flashLender: string,
        _dex: string,
        _vaultToFAssetDexPath: string[],
        _poolToVaultDexPath: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _payments: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionId: string;
              sourceAddressIndicator: string;
            };
            responseBody: {
              blockNumber: number | BN | string;
              blockTimestamp: number | BN | string;
              sourceAddressHash: string;
              spentAmount: number | BN | string;
              standardPaymentReference: string;
            };
          };
        }[],
        _agentVault: string,
        _vaultToFAssetMinDexPriceMul: number | BN | string,
        _vaultToFAssetMinDexPriceDiv: number | BN | string,
        _poolToVaultMinDexPriceMul: number | BN | string,
        _poolToVaultMinDexPriceDiv: number | BN | string,
        _flashLender: string,
        _dex: string,
        _vaultToFAssetDexPath: string[],
        _poolToVaultDexPath: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    illegalPaymentChallenge: {
      (
        _transaction: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionId: string;
              sourceAddressIndicator: string;
            };
            responseBody: {
              blockNumber: number | BN | string;
              blockTimestamp: number | BN | string;
              sourceAddressHash: string;
              spentAmount: number | BN | string;
              standardPaymentReference: string;
            };
          };
        },
        _agentVault: string,
        _vaultToFAssetMinDexPriceMul: number | BN | string,
        _vaultToFAssetMinDexPriceDiv: number | BN | string,
        _poolToVaultMinDexPriceMul: number | BN | string,
        _poolToVaultMinDexPriceDiv: number | BN | string,
        _flashLender: string,
        _dex: string,
        _vaultToFAssetDexPath: string[],
        _poolToVaultDexPath: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _transaction: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionId: string;
              sourceAddressIndicator: string;
            };
            responseBody: {
              blockNumber: number | BN | string;
              blockTimestamp: number | BN | string;
              sourceAddressHash: string;
              spentAmount: number | BN | string;
              standardPaymentReference: string;
            };
          };
        },
        _agentVault: string,
        _vaultToFAssetMinDexPriceMul: number | BN | string,
        _vaultToFAssetMinDexPriceDiv: number | BN | string,
        _poolToVaultMinDexPriceMul: number | BN | string,
        _poolToVaultMinDexPriceDiv: number | BN | string,
        _flashLender: string,
        _dex: string,
        _vaultToFAssetDexPath: string[],
        _poolToVaultDexPath: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _transaction: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionId: string;
              sourceAddressIndicator: string;
            };
            responseBody: {
              blockNumber: number | BN | string;
              blockTimestamp: number | BN | string;
              sourceAddressHash: string;
              spentAmount: number | BN | string;
              standardPaymentReference: string;
            };
          };
        },
        _agentVault: string,
        _vaultToFAssetMinDexPriceMul: number | BN | string,
        _vaultToFAssetMinDexPriceDiv: number | BN | string,
        _poolToVaultMinDexPriceMul: number | BN | string,
        _poolToVaultMinDexPriceDiv: number | BN | string,
        _flashLender: string,
        _dex: string,
        _vaultToFAssetDexPath: string[],
        _poolToVaultDexPath: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _transaction: {
          merkleProof: string[];
          data: {
            attestationType: string;
            sourceId: string;
            votingRound: number | BN | string;
            lowestUsedTimestamp: number | BN | string;
            requestBody: {
              transactionId: string;
              sourceAddressIndicator: string;
            };
            responseBody: {
              blockNumber: number | BN | string;
              blockTimestamp: number | BN | string;
              sourceAddressHash: string;
              spentAmount: number | BN | string;
              standardPaymentReference: string;
            };
          };
        },
        _agentVault: string,
        _vaultToFAssetMinDexPriceMul: number | BN | string,
        _vaultToFAssetMinDexPriceDiv: number | BN | string,
        _poolToVaultMinDexPriceMul: number | BN | string,
        _poolToVaultMinDexPriceDiv: number | BN | string,
        _flashLender: string,
        _dex: string,
        _vaultToFAssetDexPath: string[],
        _poolToVaultDexPath: string[],
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
