/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Truffle } from "./types";

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface RippleAddressValidatorContract
  extends Truffle.Contract<RippleAddressValidatorInstance> {
  "new"(
    meta?: Truffle.TransactionDetails
  ): Promise<RippleAddressValidatorInstance>;
}

export type AllEvents = never;

export interface RippleAddressValidatorInstance
  extends Truffle.ContractInstance {
  normalize(
    _underlyingAddress: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: string; 1: string }>;

  validate(
    _rippleAddress: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<boolean>;

  methods: {
    normalize(
      _underlyingAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: string; 1: string }>;

    validate(
      _rippleAddress: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<boolean>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
