stages:
  - build
  - fuzzer
  - coverage
  - test


variables:
  YARN_CACHE_DIR: "$CI_PROJECT_DIR/.yarn-cache"


include:
  - template: Jobs/SAST.gitlab-ci.yml

sast:
  needs:
  - job: run-tests
    optional: true


.rules:

  always:
    # branch pipelines
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS == null && $CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS == null'
    # MR pipelines
    - if: '$CI_OPEN_MERGE_REQUESTS != null && $CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web"'
    # Prevent duplicate MR && branch pipelines
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never

  manual-web_always:
    # branch pipelines
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS == null && $CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS == null'
      when: manual
    # MR pipelines
    - if: '$CI_OPEN_MERGE_REQUESTS != null && $CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web"'
      when: manual
    # Prevent duplicate MR && branch pipelines
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE != "web"'
      when: never


.run-on-selfhosted-runner:
  tags:
    - flarenetworks


.test-node:
  stage: test
  image: node:latest
  timeout: 3h
  rules:
  - !reference [.rules, always]
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - .yarn-cache/
        - node_modules/
      policy: pull-push


.test-node-sc:
  extends: .test-node
  variables:
    DEPLOYER_PRIVATE_KEY: "0xc5e8f61d1ab959b397eecc0a37a6517b8e67a0e7cf1f4bce5591f3ed80199122"
    GENESIS_GOVERNANCE_PRIVATE_KEY: "0x50777f5a3ce16445e63411bf1e865a2a11d5ca3c4cbc1de00808a52180bd8d3c"
    GOVERNANCE_PRIVATE_KEY: "0xd49743deccbccc5dc7baa8e69e5be03298da8688a15dd202e20f15d5e0e9a9fb"
    GOVERNANCE_PUBLIC_KEY: "0xeAD9C93b79Ae7C1591b1FB5323BD777E86e150d4"
    GOVERNANCE_EXECUTOR_PUBLIC_KEY: "0xE5904695748fe4A84b40b3fc79De2277660BD1D3"
  needs:
    - build-smart-contracts
    - job: run-tests
      optional: true
  dependencies:
    - build-smart-contracts
  before_script:
    - yarn install --frozen-lockfile --cache-folder $YARN_CACHE_DIR


run-tests:
  stage: build
  image: busybox
  rules:
  - !reference [.rules, manual-web_always]
  script: [ "true" ]


build-smart-contracts:
  stage: build
  needs: []
  image: node:latest
  before_script:
    - yarn install --frozen-lockfile --cache-folder $YARN_CACHE_DIR
  script:
    - yarn c
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - .yarn-cache/
        - node_modules/
      policy: pull-push
  rules:
  - !reference [coverage:schedule, rules]
  - !reference [fuzzer:schedule, rules]
  - !reference [.rules, manual-web_always]
  artifacts:
    paths:
      - typechain-truffle
    expire_in: 1 week


### Jobs


test-unit:
  extends: .test-node-sc
  script:
    - yarn testHH_all:unit

test-contract-integration:
  extends: .test-node-sc
  script:
    - yarn testHH_all:integration


test-linter:
  extends: .test-node-sc
  script:
    - yarn lint

coverage:schedule:
  extends:
    - .run-on-selfhosted-runner
    - .test-node-sc
  stage: coverage
  retry: 2
  script:
    - yarn cover
  rules:
  - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "coverage"'
    when: always


fuzzer:schedule:
  extends:
    - .run-on-selfhosted-runner
    - .test-node-sc
  stage: fuzzer
  timeout: 4 hours
  variables:
    NODE_OPTIONS: "--max_old_space_size=6144"
    LOOPS: 5000
    CHANGE_PRICE_AT: '300,600,...'
  script:
    - yarn testHH:fuzzer
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $SCHEDULE_NAME == "fuzzer"'
      when: always
