/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IMerkleRootStorageContract
  extends Truffle.Contract<IMerkleRootStorageInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<IMerkleRootStorageInstance>;
}

type AllEvents = never;

export interface IMerkleRootStorageInstance extends Truffle.ContractInstance {
  merkleRoot(
    _roundId: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  methods: {
    merkleRoot(
      _roundId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
