/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IContingencyPoolFactoryContract
  extends Truffle.Contract<IContingencyPoolFactoryInstance> {
  "new"(
    meta?: Truffle.TransactionDetails
  ): Promise<IContingencyPoolFactoryInstance>;
}

type AllEvents = never;

export interface IContingencyPoolFactoryInstance
  extends Truffle.ContractInstance {
  create: {
    (
      _assetManager: string,
      _agentVault: string,
      _settings: {
        underlyingAddressString: string;
        vaultCollateralToken: string;
        feeBIPS: number | BN | string;
        poolFeeShareBIPS: number | BN | string;
        mintingVaultCollateralRatioBIPS: number | BN | string;
        mintingPoolCollateralRatioBIPS: number | BN | string;
        buyFAssetByAgentFactorBIPS: number | BN | string;
        poolExitCollateralRatioBIPS: number | BN | string;
        poolTopupCollateralRatioBIPS: number | BN | string;
        poolTopupTokenPriceFactorBIPS: number | BN | string;
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _assetManager: string,
      _agentVault: string,
      _settings: {
        underlyingAddressString: string;
        vaultCollateralToken: string;
        feeBIPS: number | BN | string;
        poolFeeShareBIPS: number | BN | string;
        mintingVaultCollateralRatioBIPS: number | BN | string;
        mintingPoolCollateralRatioBIPS: number | BN | string;
        buyFAssetByAgentFactorBIPS: number | BN | string;
        poolExitCollateralRatioBIPS: number | BN | string;
        poolTopupCollateralRatioBIPS: number | BN | string;
        poolTopupTokenPriceFactorBIPS: number | BN | string;
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    sendTransaction(
      _assetManager: string,
      _agentVault: string,
      _settings: {
        underlyingAddressString: string;
        vaultCollateralToken: string;
        feeBIPS: number | BN | string;
        poolFeeShareBIPS: number | BN | string;
        mintingVaultCollateralRatioBIPS: number | BN | string;
        mintingPoolCollateralRatioBIPS: number | BN | string;
        buyFAssetByAgentFactorBIPS: number | BN | string;
        poolExitCollateralRatioBIPS: number | BN | string;
        poolTopupCollateralRatioBIPS: number | BN | string;
        poolTopupTokenPriceFactorBIPS: number | BN | string;
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _assetManager: string,
      _agentVault: string,
      _settings: {
        underlyingAddressString: string;
        vaultCollateralToken: string;
        feeBIPS: number | BN | string;
        poolFeeShareBIPS: number | BN | string;
        mintingVaultCollateralRatioBIPS: number | BN | string;
        mintingPoolCollateralRatioBIPS: number | BN | string;
        buyFAssetByAgentFactorBIPS: number | BN | string;
        poolExitCollateralRatioBIPS: number | BN | string;
        poolTopupCollateralRatioBIPS: number | BN | string;
        poolTopupTokenPriceFactorBIPS: number | BN | string;
      },
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    create: {
      (
        _assetManager: string,
        _agentVault: string,
        _settings: {
          underlyingAddressString: string;
          vaultCollateralToken: string;
          feeBIPS: number | BN | string;
          poolFeeShareBIPS: number | BN | string;
          mintingVaultCollateralRatioBIPS: number | BN | string;
          mintingPoolCollateralRatioBIPS: number | BN | string;
          buyFAssetByAgentFactorBIPS: number | BN | string;
          poolExitCollateralRatioBIPS: number | BN | string;
          poolTopupCollateralRatioBIPS: number | BN | string;
          poolTopupTokenPriceFactorBIPS: number | BN | string;
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _assetManager: string,
        _agentVault: string,
        _settings: {
          underlyingAddressString: string;
          vaultCollateralToken: string;
          feeBIPS: number | BN | string;
          poolFeeShareBIPS: number | BN | string;
          mintingVaultCollateralRatioBIPS: number | BN | string;
          mintingPoolCollateralRatioBIPS: number | BN | string;
          buyFAssetByAgentFactorBIPS: number | BN | string;
          poolExitCollateralRatioBIPS: number | BN | string;
          poolTopupCollateralRatioBIPS: number | BN | string;
          poolTopupTokenPriceFactorBIPS: number | BN | string;
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      sendTransaction(
        _assetManager: string,
        _agentVault: string,
        _settings: {
          underlyingAddressString: string;
          vaultCollateralToken: string;
          feeBIPS: number | BN | string;
          poolFeeShareBIPS: number | BN | string;
          mintingVaultCollateralRatioBIPS: number | BN | string;
          mintingPoolCollateralRatioBIPS: number | BN | string;
          buyFAssetByAgentFactorBIPS: number | BN | string;
          poolExitCollateralRatioBIPS: number | BN | string;
          poolTopupCollateralRatioBIPS: number | BN | string;
          poolTopupTokenPriceFactorBIPS: number | BN | string;
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _assetManager: string,
        _agentVault: string,
        _settings: {
          underlyingAddressString: string;
          vaultCollateralToken: string;
          feeBIPS: number | BN | string;
          poolFeeShareBIPS: number | BN | string;
          mintingVaultCollateralRatioBIPS: number | BN | string;
          mintingPoolCollateralRatioBIPS: number | BN | string;
          buyFAssetByAgentFactorBIPS: number | BN | string;
          poolExitCollateralRatioBIPS: number | BN | string;
          poolTopupCollateralRatioBIPS: number | BN | string;
          poolTopupTokenPriceFactorBIPS: number | BN | string;
        },
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
