/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface IFtsoGenesisContract
  extends Truffle.Contract<IFtsoGenesisInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<IFtsoGenesisInstance>;
}

type AllEvents = never;

export interface IFtsoGenesisInstance extends Truffle.ContractInstance {
  revealPriceSubmitter: {
    (
      _voter: string,
      _epochId: number | BN | string,
      _price: number | BN | string,
      _wNatVP: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _voter: string,
      _epochId: number | BN | string,
      _price: number | BN | string,
      _wNatVP: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<void>;
    sendTransaction(
      _voter: string,
      _epochId: number | BN | string,
      _price: number | BN | string,
      _wNatVP: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _voter: string,
      _epochId: number | BN | string,
      _price: number | BN | string,
      _wNatVP: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  wNatVotePowerCached: {
    (
      _voter: string,
      _epochId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<Truffle.TransactionResponse<AllEvents>>;
    call(
      _voter: string,
      _epochId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<BN>;
    sendTransaction(
      _voter: string,
      _epochId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
    estimateGas(
      _voter: string,
      _epochId: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<number>;
  };

  methods: {
    revealPriceSubmitter: {
      (
        _voter: string,
        _epochId: number | BN | string,
        _price: number | BN | string,
        _wNatVP: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _voter: string,
        _epochId: number | BN | string,
        _price: number | BN | string,
        _wNatVP: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<void>;
      sendTransaction(
        _voter: string,
        _epochId: number | BN | string,
        _price: number | BN | string,
        _wNatVP: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _voter: string,
        _epochId: number | BN | string,
        _price: number | BN | string,
        _wNatVP: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };

    wNatVotePowerCached: {
      (
        _voter: string,
        _epochId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<Truffle.TransactionResponse<AllEvents>>;
      call(
        _voter: string,
        _epochId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<BN>;
      sendTransaction(
        _voter: string,
        _epochId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<string>;
      estimateGas(
        _voter: string,
        _epochId: number | BN | string,
        txDetails?: Truffle.TransactionDetails
      ): Promise<number>;
    };
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
